### ISSUE TITLE
How to disable MD syntax

### ISSUE THREAD

**Issue by steven-qi** [alexdrel/i18n-react#33] opened 2017-10-07 08:53 UTC
Sorry for use this as a Q&A here, but I cannot find anything useful elsewhere.

The new MD syntax is awesome, but could cause surprising  issues if the original translation file was not MD-ready (say, a translation could contains `[]` but doesn't mean to render it to a separate paragraph).

So here I have two questions:
1. is there anyway to opt-out the MD rendering for individual translation key, e.g., an escape character, or a parameter to `translate` method?
2. is there any option to opt-out MD rendering for all keys?

**Comment by steven-qi** [comment] 2017-10-07 09:07
Well..., just realize that this library is always doing MD render from day one. But the problem remains here: how to render text as-is, especially for `[abc]`.

**Comment by alexdrel** [comment] 2017-10-07 13:37
@steven-qi, the MD syntax is the raison d'etre of this library, it can be turned off :) 
The [] syntax is one of the most useful for externalizing texts.
Of course you can clone and deactivate it. 
Otherwise the workaround is to pass literal strings as arguments as they are included as is. E.g.
```
T.setTexts({  k: "Example {v}!" }); 
<T.text text={{ key: "k", v: "[a]" }}/>
```
Renders: `` Example [a]! ``

**Comment by alexdrel** [comment] 2017-10-07 20:39
@steven-qi, I thought some more about it and while I'm still not in favor of disable MD, new MD syntax can be added to allow screening of the special cases.
And luckily \`\` is nice for it as it is similar to original MD meaning and being very rare in the wild.
I pushed new version just now - [0.6](https://github.com/alexdrel/i18n-react/releases/tag/release%2F0.6.0).

**Comment by steven-qi** [comment] 2017-10-09 06:42
@alexdrel Thanks much for the new `` syntax, love it! 👍

**Comment by steven-qi** [comment] 2017-10-09 08:48
@alexdrel checkout this one ` ``[``{val}``]`` ` (say `val` is `abc`), which will be rendered as ` [abc]``]`` `.

I guess this is due to that, v1 `maybe` test won't pass for ` ``]`` `, thus whole segment was rendered as plain text without stripping leading/trailing ` `` `.

Although I can fix it easily by change it to ` ``[``{val}] `, but just feel a bit confused, as ` `` ` is supposed to render anything between as-is. Maybe we could just change `maybe` of v1 to ``  /[\*_~\{\[\n`]/  ``

**Comment by alexdrel** [comment] 2017-10-10 17:38
Hi @steven-qi,
I'm out of town for a week - I will look into when I'll be back. I think you are right the issue is with 
*maybe* filter which I have not updated when added the new regex.

**Comment by alexdrel** [comment] 2017-10-15 21:30
Fixed in 0.6.1,  @steven-qi exactly as you suggested.

**Closed by alexdrel** 2017-10-15 21:30 UTC

**Comment by steven-qi** [comment] 2017-10-16 01:51
@alexdrel Great. Thanks!

**Comment by munkhorgil** [comment] 2018-04-22 10:50
@alexdrel Could you make MD Syntax optional? I can't even use [], ..., . in my strings.

**Comment by steven-qi** [comment] 2018-04-23 01:37
@munkhorgil Just FYI, you may wrap text into ` `` ` to make it render as-is (aka, literal).
